name: goreleaser

on:
  pull_request:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest

      - name: Install mdbook-callouts from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-callouts
          version: "v0.2.1"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'

      - name: Install mdbook d2 preprocessor
        run: go install github.com/Vaelatern/mdbook-d2-go@latest

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Driver Station
        run: sudo sh -x .release/build-ds.sh

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: driver-station.zip
          generate_release_notes: false
          fail_on_unmatched_files: true
